on:
  release:
    types: [released]
  pull_request:

name: Run Unit Tests and build packages for all target platforms

env:
  # Maven credentials for publishing the AAR
  MAVEN_REPOSITORY: https://maven.pkg.github.com/jothepro/djinni-library-template
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  # NuGet credentials for publishing the NuGet package for .NET Core
  NUGET_REPOSITORY: https://nuget.pkg.github.com/jothepro/index.json
  NUGET_API_KEY: ${{ secrets.NUGET_PASSWORD }}
  # Conan credentials for publishing the raw conan artifacts.
  CONAN_REPOSITORY: https://artifactory.jothe.pro/artifactory/api/conan/conan-private
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  SWIFTPACKAGE_GITSERVER: github.com/jothepro
  SWIFTPACKAGE_REPOSITORY: djinni-library-template-swiftpackage
  SWIFTPACKAGE_REPOSITORY_USERNAME: jothepro
  SWIFTPACKAGE_REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

jobs:
  test:
    name: Build & test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
          submodules: true
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Conan
        uses: turtlebrowser/get-conan@main
      - name: Conan install
        run: conan install -if build .
      - name: Conan build & test
        run: conan build ..
        working-directory: build

  build_android:
    name: Package for Android (AAR)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
          submodules: true
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22b
          add-to-path: false
      - name: Install Python requirements
        run: pip install -r djinni_build/requirements.txt
      - name: configure, build and package
        run: ./build.py --android x86 x86_64 armv7 armv8 --configuration release --package aar
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: publish
        run: ./gradlew publish
        working-directory: lib/platform/android/package/
      - name: set version to Doxyfile
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile-Java
      - name: generate documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'Doxyfile-Java'
      - name: Publish generated docs to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/generated/html
          branch: gh-pages
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

  build_darwin:
    name: Package for Darwin (swiftpackage)
    runs-on: macos-latest
    needs: test
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python requirements
        run: pip install -r djinni_build/requirements.txt
      - name: configure, build and package
        run: ./build.py --macos x86_64 armv8 --iphonesimulator x86_64 armv8 --iphoneos armv8 --package xcframework swiftpackage --configuration release
      - name: publish
        run: |
          git clone -–depth 1 https://$SWIFTPACKAGE_REPOSITORY_USERNAME:SWIFTPACKAGE_REPOSITORY_PASSWORD@$SWIFTPACKAGE_GITSERVER/SWIFTPACKAGE_REPOSITORY.git
          cp -r swiftpackage/* $SWIFTPACKAGE_REPOSITORY
          VERSION=`git describe --tags`
          cd $SWIFTPACKAGE_REPOSITORY
          git tag $VERSION
          git push --atomic origin main $VERSION
        working-directory: build/
      - name: set version to Doxyfile
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile-ObjC
      - name: generate documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'Doxyfile-ObjC'
      - name: Publish generated docs to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/generated/html
          branch: gh-pages
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

  build_windows:
    name: Package for Windows (NuGet)
    runs-on: windows-latest
    needs: test
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python requirements
        run: pip install -r djinni_build/requirements.txt
      - name: configure, build and package
        run: python3 ./build.py --windows x86 x86_64 armv7 armv8 --package nuget --configuration release
      - name: publish
        run: nuget push MyDjinniLibrary.*.nupkg -source $env:NUGET_REPOSITORY -ApiKey $env:NUGET_API_KEY
        working-directory: build/windows/
      - name: set version to Doxyfile
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile-CppCli
      - name: generate documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'Doxyfile-CppCli'
      - name: Publish generated docs to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/generated/html
          branch: gh-pages
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

  build_linux:
    name: Package for Linux (Conan)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python requirements
        run: pip install -r djinni_build/requirements.txt
      - name: configure, build and package
        run: ./build.py --linux x86 x86_64 armv7 armv8 --package conan --configuration release
      - name: set version to Doxyfile
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile-Cpp
      - name: generate documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'Doxyfile-Cpp'
      - name: Publish generated docs to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/generated/html
          branch: gh-pages
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}